install.packages('renv')
#renv::restore('renv.lock')
#options(renv.config.auto.snapshot = TRUE)
install.packages('devtools')
install.packages('remotes')
install.packages('rmarkdown')
install.packages('markdown')
install.packages('tidyverse')
install.packages('downloadthis')
install.packages('gganimate')
install.packages('transformr')
devtools::install_github("gadenbuie/xaringanExtra")
#Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1)
#install.packages("rstan")
install.packages('osfr', repos = 'http://cran.us.r-project.org')
install.packages('cmdstanr', repos = c('https://mc-stan.org/r-packages/', getOption('repos')))
install.packages(c("coda","mvtnorm","loo","dagitty","shape"))
devtools::install_github('rmcelreath/rethinking')
#cmdstanr::install_cmdstan()
#libglpk-dev
#install.packages(c('brms','tidybayes','rstanarm'))